[package]
name        = "librpm-sys"
description = "RPM Package Manager library FFI bindings (librpm.so)"
version     = "0.1.0"
license     = "LGPL-2.1+"
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
categories  = ["external-ffi-bindings", "os"]
keywords    = ["rpm", "linux", "redhat", "fedora", "centos"]
readme      = "README.md"
homepage    = "https://rustrpm.org/librpm-sys/"
repository  = "https://github.com/rustrpm/librpm-rs/tree/master/librpm-sys"

[badges]
circle-ci = { repository = "rustrpm/librpm-rs" }

[build-dependencies]
bindgen = "0.35"

